baseURL = 'https://mc2-center.github.io/cckp-chatbot/'
title = 'CCKP Copilot Docs'
theme = 'hugo-book'

disablePathToLower = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'light'
  BookSection = 'docs'
  BookFavicon = 'favicon.svg'
  BookRepo = 'https://github.com/mc2-center/cckp-chatbot'
  BookSearch = true
  BookComments = false
  BookPortableLinks = 'warning'

[[menu.after]]
  name = 'GitHub'
  url = 'https://github.com/mc2-center/cckp-chatbot'
  weight = 10
